config/routes.rb
Rails.application.routes.draw do
get 'profiles' => 'profiles#index'
get 'profiles/:id' => 'profiles#show', as: :profile 
  resources :tweets do
    resource :likes
  end
  resources :relationships, only: [:create, :destroy]
  
  devise_for :users
  
  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet 
end

# == Schema Information
#
# Table name: likes
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  tweet_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

# == Schema Information
#
# Table name: relationships
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  friend_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :likes
  
  validates :message, presence: true, length: { maximum: 140, too_long: 'A 
  tweet is only 140 characters max.' }
end

# == Schema Information
#
# Table name: tweets
#
#  id         :integer          not null, primary key
#  message    :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_tweets_on_user_id  (user_id)
#

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :tweets, dependent: :destroy
  has_many :relationships
  has_many :friends, through: :relationships
  
  has_many :inverse_relationships, class_name: "Relationship"
  has_many :inverse_friends, through: :inverse_relationships, source: :user
  
  has_many :likes
  
  validates :username, presence: true, uniqueness: true
  
  def likes?(tweet)
    tweet.likes.where(user_id: id).any?
  end
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string
#  username               :string
#  bio                    :text
#  location               :string
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_user_parameters, if: :devise_controller?
  
  
  protected
  
  def configure_permitted_user_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit( { roles: [] }, :email, 
    :email, :password, :password_confirmation, :name, :username, :bio, 
    :location) }
    
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit( :email,
    :password, :password_confirmation, :current_password, :name, :username,
    :bio, :location ) }
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet
  
  def create
    @tweet.likes.where(user_id: current_user.id).first_or_create
    
    redirect_back(fallback_location: root_path)
  end
  
  def destroy
    @tweet.likes.where(user_id: current_user.id).destroy_all
    
    redirect_back(fallback_location: root_path)
  end
  private
  
  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
    
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @relationship = current_user.relationships.build(friend_id: params[:friend_id])
    @friend = User.find(params[:friend_id])

    if @relationship.save
      flash[:notice] = "You're now following #{@friend.username}, don't be creepy..."
      redirect_to profile_path(params[:friend_id])
    else
      flash[:notice] = "Something went wrong, try again."
      redirect_to profile_path(params[:friend_id])
    end
  end

  def destroy
    @relationship = current_user.relationships.find(params[:id])
    @relationship.destroy
    @exfriend = User.find(params[:friend_id])

    flash[:notice] = "No longer following #{@exfriend.username}"
    redirect_to profile_path(current_user.id)
  end

  private

  def relationship_params
    params.require(:relationship).permit(:user_id, :friend_id)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: [:edit, :update, :show, :destroy]
  
  def index
    @tweets = Tweet.all
  end

  def new
    @tweet = Tweet.new
  end

  def create
  @tweet = Tweet.new(tweet_params)
    if @tweet.save
  redirect_to @tweet, notice: 'You just tweeted!'  
  else
    render :new
    end
  end
  def edit
   # @tweet = Tweet.find(params[:id])
  end
  
  def update
   # @tweet = Tweet.find(params[:id])
    
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Your tweet has been updated.'
    else
      flash.now[:alert] = 'There was a problem updating your Tweet.'
      render :edit
    end
  end

  def show
    #@tweet = Tweet.find(params[:id])
  end
  
  def destroy
    if @tweet.destroy
      redirect_to tweets_url, notice: 'Tweet destroyed.'
  else
    flash.now[:alert]= 'Something went wrong. Your tweet escaped destruction. Try again.'
    end
  end
  
  private
  
  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end
  
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Twitter For Goats</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to 'Tweets', tweets_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Profiles', profiles_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav my-2">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to 'Update Profile', edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_notices.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <% if notice %>
        <div class="notice alert alert-primary" role="alert"><%= notice %></div>
      <% elsif alert %>
        <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>      
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialStatus</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<h1>All Users</h1>

<% @users.each do |user| %>
  <%= link_to user.username, profile_path(user) %><br>
<% end %>

app/views/profiles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <h3><%= @user.name %></h3>
      <h5><%= @user.username %></h5>
      <h5><p><%= sanitize(@user.bio) %></p></h5>
      <h5><%= @user.location %></h5>
      <h5>Joined on <%= @user.created_at.stamp("November 1, 1804") %></h5>

      <% if @user.id != current_user.id %>
        <% if current_user.friends.include?(@user) %>
          <%= link_to 'Unfollow', relationship_path(current_user.relationships.find_by_friend_id(@user), friend_id: @user), method: :delete, class: 'btn btn-secondary mb-3' %>
        <% else %>
          <%= link_to 'Follow', relationships_path(friend_id: @user), method: :post, class: "btn btn-secondary mb-3" %>
        <% end %>
      <% end %>
      <br>

      <%= @user.relationships.count %> Following
      <br>
      <% @user.relationships.each do |relationship| %>
        <%= link_to relationship.friend.name, profile_path(relationship.friend) %> <br>
      <% end %>

      <br><br>

      <%= pluralize(@user.inverse_relationships.count, "Follower") %>
      <br>
      <% @user.inverse_friends.each do |friend| %>
        <%= link_to friend.name, profile_path(friend) %><br>
      <% end %>
    </div>

    <div class="col-7">
      <div class="card">
        <% @user.tweets.each do |tweet| %>
          <div class="card-body">
            <strong><%= tweet.user.username %> </strong><small>tweeted <%= time_ago_in_words(tweet.created_at) %></small>

            <br><br>

            <%= tweet.message %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_likes.html.erb
<% if current_user.likes?(tweet) %>
  <%= link_to 'Unlike', tweet_likes_path(@tweet), method: :delete, class: 'btn
  btn_secondary' %>
<% else %>
  <%= link_to 'Like', tweet_likes_path(@tweet), method: :post, class: 'btn
  btn_secondary' %>
<% end %>

<%= @tweet.likes.count %>
<br>

Liked by:
  <% @tweet.likes.each do |like| %>
  <br>
   <%= like.user.username %>
  <br>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>

  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@tweet.errors.count, 'error') %> prohibited this tweet
        from being saved:
      </h2>
      <ul>
        <%= @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :message %> <br>
    <%= f.text_field :message, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= f.hidden_field :user_id, value: current_user.id, class: "form-control" %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-info" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= render 'form' %>

<%= link_to 'All the Tweets', tweets_path, class: "btn btn-secondary" %>
 

app/views/tweets/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1 class="text-center">All the tweets in the Universe</h1>
      
      <%= link_to 'New Tweet', new_tweet_path, class: 'btn btn-primary mb-3' %>
      <table class="table table-striped table-hover">
        <thead class="thead-dark">
          <tr>
            <th>Message</th>
            <th>User</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        
        <tbody>
          <% @tweets.each do |tweet| %>
          <tr>
            <td><%= tweet.message %></td>
            <td><%= tweet.user.try(:username) %></td>
            <td><%= link_to fa_icon('eye', text: 'Show'),
                            tweet,
                            class: "btn btn-sm" %></td>
            <td><%= link_to fa_icon('pencil', text: 'Edit'),
                            edit_tweet_path(tweet),
                            class: "btn btn-sm btn_secondary" %></td>
            <td><%= link_to fa_icon('trash-o', text: 'Destroy'),
                            tweet,
                            method: :delete,
                            data: {confirm: 'Are you sure?'},
                            class: "btn btn-sm btn_secondary" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'All The Tweets', tweets_path, class: "btn btn_default" %>

app/views/tweets/show.html.erb
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-6 text-center">
      <p>
        <strong>Message:</strong> <%= sanitize(@tweet.message) %>
      </p>

      <p>
        <strong>User: </strong> <%= @tweet.user.username if @tweet.user %>
      </p>

      <%= render 'shared/likes' %>
      <br><br>
      <%= link_to 'Edit', edit_tweet_path(@tweet), class: "btn btn-secondary" %>
      <%= link_to 'See All The Tweets', tweets_path, class: "btn btn-secondary" %>
    </div>
  </div>
</div>